---
- hosts: localhost
  remote_user: root

  tasks:
  - name: Create security group
    ec2_group:
        name: ec2-slfinal
        description: ec2-slfinal security group
        region: us-east-1
        aws_access_key: ASIA6BMIV6O7FYWXE4HG
        aws_secret_key: 4Txy0E+MfvukAr/w83pIFEYIxKif5vDSdKvlabI0
        security_token: FwoGZXIvYXdzEIP//////////wEaDL/XBi/NGQMSZwv3GSK5AdfnaPmuqpm+Vkhhh76CM1BCr/TdsM/Jo2FBMjDfN5X6/F6Pe/EvNqPvU/Q4HSyuihpOxTusEEuqiKXxSKpKy2grYxvgb5t4kOjIs7GQ9en1nIg4OU6Pi7Ge4TDdNpbCZiUHBqfM8rYNxbvs9jldX3Cgg63QTQNaE23Kf4M/Wt5Oqqtw6gILdVLg+pUBLlUZjqL0xFREYul2no+m+oSfF8I0s3SThsEnrJHq8CO9Er7eT3kG0u3Gvi+yKLvOxpYGMi3hlwmlgnsaFA7Y1ULrJ/Ss22V4EcoX1sPHeRrF26ph8UnjERwSyLvmdAX+XXY=
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    
    register: firewall_sg
    

  - name: Create a new EC2 key
    ec2_key:
      name: ec2-slfinal-key
      region: us-east-1
      aws_access_key: ASIA6BMIV6O7FYWXE4HG
      aws_secret_key: 4Txy0E+MfvukAr/w83pIFEYIxKif5vDSdKvlabI0
      security_token: FwoGZXIvYXdzEIP//////////wEaDL/XBi/NGQMSZwv3GSK5AdfnaPmuqpm+Vkhhh76CM1BCr/TdsM/Jo2FBMjDfN5X6/F6Pe/EvNqPvU/Q4HSyuihpOxTusEEuqiKXxSKpKy2grYxvgb5t4kOjIs7GQ9en1nIg4OU6Pi7Ge4TDdNpbCZiUHBqfM8rYNxbvs9jldX3Cgg63QTQNaE23Kf4M/Wt5Oqqtw6gILdVLg+pUBLlUZjqL0xFREYul2no+m+oSfF8I0s3SThsEnrJHq8CO9Er7eT3kG0u3Gvi+yKLvOxpYGMi3hlwmlgnsaFA7Y1ULrJ/Ss22V4EcoX1sPHeRrF26ph8UnjERwSyLvmdAX+XXY=      key_material: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    

  - name: Create an EC2 instance
    ec2:
      key_name: ec2-slfinal-key
      region: us-east-1
      group_id: "{{ firewall_sg.group_id }}"
      instance_type: t2.micro
      image: ami-0813288835c686b96
      wait: yes
      instance_tags:
          Name: ec2-slfinal-key
      aws_access_key: ASIA6BMIV6O7FYWXE4HG
      aws_secret_key: 4Txy0E+MfvukAr/w83pIFEYIxKif5vDSdKvlabI0
      security_token: FwoGZXIvYXdzEIP//////////wEaDL/XBi/NGQMSZwv3GSK5AdfnaPmuqpm+Vkhhh76CM1BCr/TdsM/Jo2FBMjDfN5X6/F6Pe/EvNqPvU/Q4HSyuihpOxTusEEuqiKXxSKpKy2grYxvgb5t4kOjIs7GQ9en1nIg4OU6Pi7Ge4TDdNpbCZiUHBqfM8rYNxbvs9jldX3Cgg63QTQNaE23Kf4M/Wt5Oqqtw6gILdVLg+pUBLlUZjqL0xFREYul2no+m+oSfF8I0s3SThsEnrJHq8CO9Er7eT3kG0u3Gvi+yKLvOxpYGMi3hlwmlgnsaFA7Y1ULrJ/Ss22V4EcoX1sPHeRrF26ph8UnjERwSyLvmdAX+XXY=      key_material: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

      count_tag: Name
      exact_count: 1
      vpc_subnet_id: subnet-008880fbaf399fc96
      assign_public_ip: yes
    register: ec2
